import keyMirror from 'keymirror';

export default keyMirror({
  REQUEST_DEPARTMENT: null,
  REQUEST_DEPARTMENT_SUCCESS: null,
  REQUEST_DEPARTMENT_ERROR: null,

  REQUEST_DOCTOR: null,
  REQUEST_DOCTOR_SUCCESS: null,
  REQUEST_DOCTOR_ERROR: null,

  ADD_NEW_DOCTOR: null,

  SAVE_NEW_DOCTOR: null,
  SAVE_NEW_DOCTOR_SUCCESS: null,
  SAVE_NEW_DOCTOR_ERROR: null,

  REMOVE_DOCTOR: null,
  REMOVE_DOCTOR_SUCCESS: null,
  REMOVE_DOCTOR_ERROR: null
});
